jason-patch-1
breaking-barriers-tamu/breaking_barriers pull request #120
Opened 2023-11-10 07:17 UTC by JasonIsAzn

2023-11-10 23:34 UTC, jrr2024 requested changes
check your line spacing in

2023-11-10 23:34 UTC, jrr2024 commented on app/views/layouts/application.html.erb
check your line spacing on the div tag

2023-11-10 23:34 UTC, jrr2024 commented on app/helpers/application_helper.rb
I like these methods being globally available since they can be useful elsewhere, but truncate_text needs a more descriptive name if it's going to live in ApplicationHelper.

2023-11-12 06:15 UTC, JasonIsAzn commented on app/views/layouts/application.html.erb
#0e40c49

2023-11-12 06:15 UTC, JasonIsAzn commented on app/helpers/application_helper.rb
b5fe984

2023-11-12 07:31 UTC, jrr2024 commented
LGTM

2023-11-12 07:31 UTC, merged

2023-11-12 07:31 UTC, jrr2024 reviewed
LGTM